# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyboard_id', models.IntegerField(default=1)),
                ('current_episode', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='smuser',
            name='active_storyboard_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storyboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
