# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190421_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='smuser',
            name='rt_api_key',
            field=models.CharField(default='', max_length=611),
        ),
    ]
