# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_smuser_rt_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='smuser',
            name='pulse_goal',
            field=models.IntegerField(default=60),
        ),
    ]
